"""Render meeting minutes + transcript into a PDF.

Uses bundled **DejaVu** (Unicode) TTFs rather than fpdf2's latin-1-only core
fonts, so accented names and non-latin scripts (Cyrillic, Greek, and the many
other scripts DejaVu covers) render correctly instead of being replaced with
``?``. DejaVu does *not* cover CJK or pictographic emoji; those characters
degrade to a missing-glyph box -- never a lossy ``?`` substitution.
"""

from pathlib import Path

from fpdf import FPDF
from fpdf.enums import XPos, YPos

from src.contracts import Minutes

_FONT_DIR = Path(__file__).resolve().parent.parent / "assets" / "fonts"

# Palette
_ACCENT = (37, 99, 235)  # blue: title + section headings + speaker prefix
_MUTED = (110, 110, 110)  # meta line, footer, "None recorded."
_RULE = (210, 210, 210)  # hairline rules


class _MeetingPDF(FPDF):
    """FPDF with the bundled DejaVu families registered and a page-number footer."""

    def __init__(self) -> None:
        super().__init__()
        self.add_font("DejaVu", "", str(_FONT_DIR / "DejaVuSans.ttf"))
        self.add_font("DejaVu", "B", str(_FONT_DIR / "DejaVuSans-Bold.ttf"))
        self.add_font("DejaVuMono", "", str(_FONT_DIR / "DejaVuSansMono.ttf"))
        self.add_font("DejaVuMono", "B", str(_FONT_DIR / "DejaVuSansMono-Bold.ttf"))

    def footer(self) -> None:
        self.set_y(-14)
        self.set_font("DejaVu", "", 8)
        self.set_text_color(*_MUTED)
        # Left: attribution. Right (same line): page X of Y ({nb} = total pages).
        self.set_x(self.l_margin)
        self.cell(0, 8, "Generated by Misty", align="L", new_x=XPos.LMARGIN, new_y=YPos.TOP)
        self.cell(0, 8, f"Page {self.page_no()} of {{nb}}", align="R")
        self.set_text_color(0, 0, 0)


def _line(pdf: FPDF, h: float, text: str) -> None:
    """multi_cell wrapper that always returns the cursor to the left margin."""
    pdf.multi_cell(0, h, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def _rule(pdf: FPDF, gap_above: float = 1.0, gap_below: float = 0.0) -> None:
    pdf.set_draw_color(*_RULE)
    y = pdf.get_y() + gap_above
    pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
    pdf.set_y(y + gap_below)


def _heading(pdf: FPDF, text: str) -> None:
    pdf.ln(3)
    pdf.set_font("DejaVu", "B", 13)
    pdf.set_text_color(*_ACCENT)
    _line(pdf, 7, text)
    pdf.set_text_color(0, 0, 0)


def _muted_line(pdf: FPDF, text: str) -> None:
    pdf.set_text_color(*_MUTED)
    _line(pdf, 6, text)
    pdf.set_text_color(0, 0, 0)


def _bulleted(pdf: FPDF, items: list[str]) -> None:
    pdf.set_font("DejaVu", "", 11)
    if not items:
        _muted_line(pdf, "None recorded.")
        return
    for item in items:
        _line(pdf, 6, f"• {item}")  # • bullet (real Unicode now that fonts allow it)


def _transcript(pdf: FPDF, transcript: str) -> None:
    """Render the transcript as a chat log: each turn's ``[ts] Speaker:`` prefix
    in bold accent, the utterance in regular mono, a blank line between turns.

    ``assemble_transcript`` emits one turn per line as ``[HH:MM:SS] speaker: text``.
    Lines that don't match that shape are printed verbatim in regular mono.
    """
    pdf.set_font("DejaVuMono", "", 9)
    lines = [ln for ln in (transcript or "").split("\n") if ln.strip()]
    if not lines:
        pdf.set_font("DejaVu", "", 11)
        _muted_line(pdf, "None recorded.")
        return

    for line in lines:
        prefix = None
        rest = line
        # Split "[ts] speaker: text" into a bold "[ts] speaker:" prefix + " text".
        if line.startswith("[") and "] " in line:
            ts, after = line.split("] ", 1)
            speaker, sep, text = after.partition(": ")
            if sep:
                prefix = f"{ts}] {speaker}: "
                rest = text

        if prefix is not None:
            pdf.set_font("DejaVuMono", "B", 9)
            pdf.set_text_color(*_ACCENT)
            pdf.write(4.6, prefix)
            pdf.set_font("DejaVuMono", "", 9)
            pdf.set_text_color(0, 0, 0)
            pdf.write(4.6, rest)
        else:
            pdf.write(4.6, line)
        pdf.ln(7)  # end this turn + blank-line separation before the next


def render_meeting_pdf(minutes: Minutes, transcript: str, meta: dict) -> bytes:
    pdf = _MeetingPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # Title + rule
    pdf.set_font("DejaVu", "B", 20)
    pdf.set_text_color(*_ACCENT)
    _line(pdf, 10, meta.get("title", "Meeting Minutes"))
    pdf.set_text_color(0, 0, 0)
    _rule(pdf, gap_above=1, gap_below=4)

    # Meta header
    started_at = meta.get("started_at", "")
    duration_label = meta.get("duration_label", "")
    participants = meta.get("participants", []) or []
    pdf.set_font("DejaVu", "", 10)
    pdf.set_text_color(*_MUTED)
    _line(pdf, 5, f"Started: {started_at}    Duration: {duration_label}")
    _line(pdf, 5, f"Participants: {', '.join(participants) if participants else 'None recorded.'}")
    pdf.set_text_color(0, 0, 0)

    # Summary
    _heading(pdf, "Summary")
    pdf.set_font("DejaVu", "", 11)
    if minutes.summary:
        _line(pdf, 6, minutes.summary)
    else:
        _muted_line(pdf, "None recorded.")

    # Decisions
    _heading(pdf, "Decisions")
    _bulleted(pdf, minutes.decisions)

    # Action Items
    _heading(pdf, "Action Items")
    _bulleted(pdf, minutes.action_items)

    # Full Transcript
    _heading(pdf, "Full Transcript")
    _transcript(pdf, transcript)

    return bytes(pdf.output())
