"""Render meeting minutes + transcript into a PDF.

Uses bundled **DejaVu** (Unicode) TTFs rather than fpdf2's latin-1-only core
fonts, so accented names and non-latin scripts (Cyrillic, Greek, and the many
other scripts DejaVu covers) render correctly instead of being replaced with
``?``. DejaVu does *not* cover CJK or pictographic emoji; those characters
degrade to a missing-glyph box -- never a lossy ``?`` substitution.

Structured sections are laid out as tables: the meta header (key/value), action
items (a checkbox checklist), and the transcript (Time / Speaker / Text, with
the heading row repeated on every page). Free-form sections (summary,
decisions) stay as prose / bullets.
"""

from pathlib import Path

from fpdf import FPDF
from fpdf.enums import XPos, YPos
from fpdf.fonts import FontFace

from src.contracts import Minutes

_FONT_DIR = Path(__file__).resolve().parent.parent / "assets" / "fonts"

# Palette
_ACCENT = (37, 99, 235)  # blue: title + section headings + table headers
_MUTED = (110, 110, 110)  # meta values, footer, "None recorded."
_LABEL = (60, 60, 60)  # meta labels
_RULE = (210, 210, 210)  # hairline rules
_STRIPE = (244, 246, 250)  # zebra fill for transcript rows
_WHITE = (255, 255, 255)


class _MeetingPDF(FPDF):
    """FPDF with the bundled DejaVu families registered and a page-number footer."""

    def __init__(self) -> None:
        super().__init__()
        self.add_font("DejaVu", "", str(_FONT_DIR / "DejaVuSans.ttf"))
        self.add_font("DejaVu", "B", str(_FONT_DIR / "DejaVuSans-Bold.ttf"))
        self.add_font("DejaVuMono", "", str(_FONT_DIR / "DejaVuSansMono.ttf"))
        self.add_font("DejaVuMono", "B", str(_FONT_DIR / "DejaVuSansMono-Bold.ttf"))

    def footer(self) -> None:
        self.set_y(-14)
        self.set_font("DejaVu", "", 8)
        self.set_text_color(*_MUTED)
        # Left: attribution. Right (same line): page X of Y ({nb} = total pages).
        self.set_x(self.l_margin)
        self.cell(0, 8, "Generated by Misty", align="L", new_x=XPos.LMARGIN, new_y=YPos.TOP)
        self.cell(0, 8, f"Page {self.page_no()} of {{nb}}", align="R")
        self.set_text_color(0, 0, 0)


def _line(pdf: FPDF, h: float, text: str) -> None:
    """multi_cell wrapper that always returns the cursor to the left margin."""
    pdf.multi_cell(0, h, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def _rule(pdf: FPDF, gap_above: float = 1.0, gap_below: float = 0.0) -> None:
    pdf.set_draw_color(*_RULE)
    y = pdf.get_y() + gap_above
    pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
    pdf.set_y(y + gap_below)


def _heading(pdf: FPDF, text: str) -> None:
    pdf.ln(3)
    pdf.set_font("DejaVu", "B", 13)
    pdf.set_text_color(*_ACCENT)
    _line(pdf, 7, text)
    pdf.set_text_color(0, 0, 0)


def _muted_line(pdf: FPDF, text: str) -> None:
    pdf.set_font("DejaVu", "", 11)
    pdf.set_text_color(*_MUTED)
    _line(pdf, 6, text)
    pdf.set_text_color(0, 0, 0)


def _meta_table(pdf: FPDF, rows: list[tuple[str, str]]) -> None:
    pdf.set_font("DejaVu", "", 10)
    with pdf.table(
        borders_layout="NONE",
        first_row_as_headings=False,
        col_widths=(24, 128),
        text_align=("LEFT", "LEFT"),
        line_height=5.5,
        width=pdf.epw,
    ) as table:
        for label, value in rows:
            row = table.row()
            row.cell(label, style=FontFace(emphasis="BOLD", color=_LABEL))
            row.cell(value, style=FontFace(color=_MUTED))


def _bulleted(pdf: FPDF, items: list[str]) -> None:
    pdf.set_font("DejaVu", "", 11)
    if not items:
        _muted_line(pdf, "None recorded.")
        return
    for item in items:
        _line(pdf, 6, f"• {item}")  # • bullet (real Unicode now that fonts allow it)


def _action_items(pdf: FPDF, items: list[str]) -> None:
    if not items:
        _muted_line(pdf, "None recorded.")
        return
    pdf.set_font("DejaVu", "", 11)
    with pdf.table(
        borders_layout="NONE",
        first_row_as_headings=False,
        col_widths=(7, 145),
        text_align=("CENTER", "LEFT"),
        line_height=6,
        width=pdf.epw,
    ) as table:
        for item in items:
            row = table.row()
            row.cell("☐")  # ballot box: an open checkbox
            row.cell(item)


def _parse_turn(line: str) -> tuple[str, str, str]:
    """Split an ``assemble_transcript`` line ``[HH:MM:SS] speaker: text`` into
    ``(time, speaker, text)``. Lines that don't match go entirely in the text
    column with empty time/speaker."""
    if line.startswith("[") and "] " in line:
        ts, after = line.split("] ", 1)
        speaker, sep, text = after.partition(": ")
        if sep:
            return ts.lstrip("[").strip(), speaker.strip(), text.strip()
    return "", "", line.strip()


def _transcript(pdf: FPDF, transcript: str) -> None:
    lines = [ln for ln in (transcript or "").split("\n") if ln.strip()]
    if not lines:
        _muted_line(pdf, "None recorded.")
        return
    pdf.set_font("DejaVu", "", 9)
    with pdf.table(
        borders_layout="HORIZONTAL_LINES",
        headings_style=FontFace(emphasis="BOLD", color=_WHITE, fill_color=_ACCENT),
        col_widths=(16, 26, 110),
        text_align=("LEFT", "LEFT", "LEFT"),
        cell_fill_mode="ROWS",
        cell_fill_color=_STRIPE,
        line_height=5,
        width=pdf.epw,
    ) as table:
        table.row(("Time", "Speaker", "Text"))
        for line in lines:
            ts, speaker, text = _parse_turn(line)
            row = table.row()
            row.cell(ts, style=FontFace(family="DejaVuMono"))
            row.cell(speaker, style=FontFace(emphasis="BOLD"))
            row.cell(text)


def render_meeting_pdf(minutes: Minutes, transcript: str, meta: dict) -> bytes:
    pdf = _MeetingPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # Title + rule
    pdf.set_font("DejaVu", "B", 20)
    pdf.set_text_color(*_ACCENT)
    _line(pdf, 10, meta.get("title", "Meeting Minutes"))
    pdf.set_text_color(0, 0, 0)
    _rule(pdf, gap_above=1, gap_below=4)

    # Meta header (key/value table)
    participants = meta.get("participants", []) or []
    _meta_table(
        pdf,
        [
            ("Started", str(meta.get("started_at", "") or "-")),
            ("Duration", str(meta.get("duration_label", "") or "-")),
            ("Participants", ", ".join(participants) if participants else "None recorded."),
        ],
    )

    # Summary
    _heading(pdf, "Summary")
    if minutes.summary:
        pdf.set_font("DejaVu", "", 11)
        _line(pdf, 6, minutes.summary)
    else:
        _muted_line(pdf, "None recorded.")

    # Decisions (bullets)
    _heading(pdf, "Decisions")
    _bulleted(pdf, minutes.decisions)

    # Action Items (checklist table)
    _heading(pdf, "Action Items")
    _action_items(pdf, minutes.action_items)

    # Full Transcript (Time / Speaker / Text table)
    _heading(pdf, "Full Transcript")
    _transcript(pdf, transcript)

    return bytes(pdf.output())
